spring:
  mail:
    host: smtp.gmail.com
    port: '587'
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: 'true'
          auth: 'true'
  datasource:
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everyday?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
file:
  dir: ${FILE_DIR}
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  error:
    include-message: always
